### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by askingalot** [nss-day-cohort-41/tabloid-fullstack-elvis_spotters#2]
As a user I would like to be able to logout of the system so that I can ensure that no one else who uses my computer will have access to my Tabloid account.

**Given** an authenticated user is in the Tabloid application  
**When** they select the `Logout` option from the menu  
**Then** they should be logged out of the system  
**And** they should be directed to the home page

**Comment by dLars99** [comment]
Complete upon arrival
